services:
  dev-cuda-only:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        BASE_STAGE: cuda-only
        CUDA_VERSION: ${CUDA_VERSION}
        OS_VERSION: ${OS_VERSION}
        OPENCV_VERSION: ${OPENCV_VERSION}
        UID: ${UID:-1000}
        GID: ${UID:-1000}
        USERNAME: ${USERNAME:-ubuntu}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
    runtime: nvidia
    command: /bin/bash
    volumes:
      - ${DATA_DIR}:/shared

  dev-cuda-cudacodec:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        BASE_STAGE: cuda-cudacodec
        CUDA_VERSION: ${CUDA_VERSION}
        OS_VERSION: ${OS_VERSION}
        OPENCV_VERSION: ${OPENCV_VERSION}
        UID: ${UID:-1000}
        GID: ${UID:-1000}
        USERNAME: ${USERNAME:-ubuntu}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
    runtime: nvidia
    command: /bin/bash
    volumes:
      - ${DATA_DIR}:/shared

  dev-cuda-cudacodec-nonfree:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        BASE_STAGE: cuda-cudacodec-nonfree
        CUDA_VERSION: ${CUDA_VERSION}
        OS_VERSION: ${OS_VERSION}
        OPENCV_VERSION: ${OPENCV_VERSION}
        UID: ${UID:-1000}
        GID: ${UID:-1000}
        USERNAME: ${USERNAME:-ubuntu}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
    runtime: nvidia
    command: /bin/bash
    volumes:
      - ${DATA_DIR}:/shared
